[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Encoding = "gzip"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Encoding = "gzip"